package ru.src.logic.implementation;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;

import java.util.HashMap;
import java.util.LinkedHashMap;

public class ListConstants {
    public static final ObservableList<String> MEMBER_STATUS_LIST = FXCollections.observableArrayList();
    public static final ObservableList<String> ORGANIZATION_FORM_LIST = FXCollections.observableArrayList();
    public static final ObservableList<String> ECONOMIC_SECTOR_LIST = FXCollections.observableArrayList();
    public static final ObservableList<String> OWNERSHIP_FORM_LIST= FXCollections.observableArrayList();
    public static final ObservableList<String> ACTIVITY_TYPE_LIST = FXCollections.observableArrayList();
    public static final ObservableList<String> BUSINESS_FORM_LIST = FXCollections.observableArrayList();
    public static final ObservableList<String> INTERESTING_LIST = FXCollections.observableArrayList();
    public static final ObservableList<String> VED_LIST = FXCollections.observableArrayList();
    public static final ObservableList<String> DEDB_STATUS_LIST = FXCollections.observableArrayList();
    public static final ObservableList<String> DISTRICT_LIST = FXCollections.observableArrayList();
    public static final LinkedHashMap<String, Integer> REGION_MAP = new LinkedHashMap<>();
    public static final LinkedHashMap<String, Integer> MONTHS_LIST = new LinkedHashMap<>();
    public static final ObservableList<String> FIND_PARAMS_LIST = FXCollections.observableArrayList();
    public static final ObservableList<String> PAYMENT_LIST = FXCollections.observableArrayList();
    public static final ObservableList<String> RECEIVE_LIST = FXCollections.observableArrayList();
    public static final ObservableList<Integer> PAGE_SIZE = FXCollections.observableArrayList();

    static {
        MEMBER_STATUS_LIST.add("Актуально стабильно");
        MEMBER_STATUS_LIST.add("Актуально нестабильно");
        MEMBER_STATUS_LIST.add("Актуально долг 1 год");
        MEMBER_STATUS_LIST.add("Актуально долг 2 года");
        MEMBER_STATUS_LIST.add("Актуально долг 3 года");
        MEMBER_STATUS_LIST.add("Заявление на исключение");
        MEMBER_STATUS_LIST.add("Деятельность прекращена");
        MEMBER_STATUS_LIST.add("Потеря связи");
        MEMBER_STATUS_LIST.add("Смена формы собственности");
        MEMBER_STATUS_LIST.add("На исключение");

        ORGANIZATION_FORM_LIST.add("ООО");
        ORGANIZATION_FORM_LIST.add("ПАО");
        ORGANIZATION_FORM_LIST.add("АО");
        ORGANIZATION_FORM_LIST.add("ИАО");
        ORGANIZATION_FORM_LIST.add("ИП");
        ORGANIZATION_FORM_LIST.add("НП");
        ORGANIZATION_FORM_LIST.add("ОАО");
        ORGANIZATION_FORM_LIST.add("ЗАО");
        ORGANIZATION_FORM_LIST.add("СРО");
        ORGANIZATION_FORM_LIST.add("ФОНД");
        ORGANIZATION_FORM_LIST.add("Ассоциация");
        ORGANIZATION_FORM_LIST.add("Союз");
        ORGANIZATION_FORM_LIST.add("Объединение");
        ORGANIZATION_FORM_LIST.add("Самозанятый");
        ORGANIZATION_FORM_LIST.add("ОУ");
        ORGANIZATION_FORM_LIST.add("АНО");
        ORGANIZATION_FORM_LIST.add("Бюджетное учреждение");
        ORGANIZATION_FORM_LIST.add("Госучреждение");

        ECONOMIC_SECTOR_LIST.add("Торговля");
        ECONOMIC_SECTOR_LIST.add("Услуги");
        ECONOMIC_SECTOR_LIST.add("Производство");
        ECONOMIC_SECTOR_LIST.add("Сельскохозяйственная деятельность");
        ECONOMIC_SECTOR_LIST.add("Рыбный промысел");
        ECONOMIC_SECTOR_LIST.add("Лесное хозяйство");
        ECONOMIC_SECTOR_LIST.add("Строительство");
        ECONOMIC_SECTOR_LIST.add("Транспорт");
        ECONOMIC_SECTOR_LIST.add("Связь");
        ECONOMIC_SECTOR_LIST.add("Образование");
        ECONOMIC_SECTOR_LIST.add("Недвижимость");
        ECONOMIC_SECTOR_LIST.add("Бытовое обслуживание");
        ECONOMIC_SECTOR_LIST.add("Полиграфия и издательство");
        ECONOMIC_SECTOR_LIST.add("Туризм");
        ECONOMIC_SECTOR_LIST.add("Компьютерные услуги");
        ECONOMIC_SECTOR_LIST.add("Общественное питание");
        ECONOMIC_SECTOR_LIST.add("Иное");

        OWNERSHIP_FORM_LIST.add("Частная");
        OWNERSHIP_FORM_LIST.add("Государственная");
        OWNERSHIP_FORM_LIST.add("Смешанная");

        ACTIVITY_TYPE_LIST.add("Коммерческая");
        ACTIVITY_TYPE_LIST.add("Не коммерческая");

        BUSINESS_FORM_LIST.add("Микробизнес (<15)");
        BUSINESS_FORM_LIST.add("Малый бизнес (15-100)");
        BUSINESS_FORM_LIST.add("Средний бизнес (101-250)");
        BUSINESS_FORM_LIST.add("Крупный бизнес (>250)");

        INTERESTING_LIST.add("Интересует");
        INTERESTING_LIST.add("Не интересует");

        VED_LIST.add("Да");
        VED_LIST.add("Нет");

        DEDB_STATUS_LIST.add("Имеется");
        DEDB_STATUS_LIST.add("Отсутствует");

        DISTRICT_LIST.add("Аннинский район");
        DISTRICT_LIST.add("Бобровский район");
        DISTRICT_LIST.add("Богучарский район");
        DISTRICT_LIST.add("Борисоглебск Городской округ");
        DISTRICT_LIST.add("Бутурлиновский район");
        DISTRICT_LIST.add("Верхнемамонский район");
        DISTRICT_LIST.add("Верхнехавский район");
        DISTRICT_LIST.add("Воробьевский район");
        DISTRICT_LIST.add("Воронеж Городской округ");
        DISTRICT_LIST.add("Грибановский район");
        DISTRICT_LIST.add("Калачеевский район");
        DISTRICT_LIST.add("Каменский район");
        DISTRICT_LIST.add("Кантемировский район");
        DISTRICT_LIST.add("Каширский район");
        DISTRICT_LIST.add("Лискинский район");
        DISTRICT_LIST.add("Нижнедевицкий район");
        DISTRICT_LIST.add("Нововоронеж Городской округ");
        DISTRICT_LIST.add("Новоусманский район");
        DISTRICT_LIST.add("Новохоперский район");
        DISTRICT_LIST.add("Ольховатский район");
        DISTRICT_LIST.add("Острогожский район");
        DISTRICT_LIST.add("Павловский район");
        DISTRICT_LIST.add("Панинский район");
        DISTRICT_LIST.add("Петропавловский район");
        DISTRICT_LIST.add("Поворинский район");
        DISTRICT_LIST.add("Подгоренский район");
        DISTRICT_LIST.add("Рамонский район");
        DISTRICT_LIST.add("Репьевский район");
        DISTRICT_LIST.add("Россошанский район");
        DISTRICT_LIST.add("Семилукский район");
        DISTRICT_LIST.add("Таловский район");
        DISTRICT_LIST.add("Терновский район");
        DISTRICT_LIST.add("Хохольский район");
        DISTRICT_LIST.add("Эртильский район");

        REGION_MAP.put("Республика Адыгея", 1);
        REGION_MAP.put("Республика Башкортостан", 2);
        REGION_MAP.put("Республика Бурятия", 3);
        REGION_MAP.put("Республика Алтай", 4);
        REGION_MAP.put("Республика Дагестан", 5);
        REGION_MAP.put("Республика Ингушетия", 6);
        REGION_MAP.put("Кабардино-Балкарская Республика", 7);
        REGION_MAP.put("Республика Калмыкия", 8);
        REGION_MAP.put("Карачаево-Черкесская Республика", 9);
        REGION_MAP.put("Республика Карелия", 10);
        REGION_MAP.put("Республика Коми", 11);
        REGION_MAP.put("Республика Марий Эл", 12);
        REGION_MAP.put("Республика Мордовия", 13);
        REGION_MAP.put("Республика Саха (Якутия)", 14);
        REGION_MAP.put("Республика Северная Осетия - Алания", 15);
        REGION_MAP.put("Республика Татарстан (Татарстан)", 16);
        REGION_MAP.put("Республика Тыва", 17);
        REGION_MAP.put("Удмуртская Республика", 18);
        REGION_MAP.put("Республика Хакасия", 19);
        REGION_MAP.put("Чеченская Республика", 20);
        REGION_MAP.put("Чувашская Республика - Чувашия", 21);
        REGION_MAP.put("Алтайский край", 22);
        REGION_MAP.put("Краснодарский край", 23);
        REGION_MAP.put("Красноярский край", 24);
        REGION_MAP.put("Приморский край", 25);
        REGION_MAP.put("Ставропольский край", 26);
        REGION_MAP.put("Хабаровский край", 27);
        REGION_MAP.put("Амурская область", 28);
        REGION_MAP.put("Архангельская область", 29);
        REGION_MAP.put("Астраханская область", 30);
        REGION_MAP.put("Белгородская область", 31);
        REGION_MAP.put("Брянская область", 32);
        REGION_MAP.put("Владимирская область", 33);
        REGION_MAP.put("Волгоградская область", 34);
        REGION_MAP.put("Вологодская область", 35);
        REGION_MAP.put("Воронежская область", 36);
        REGION_MAP.put("Ивановская область", 37);
        REGION_MAP.put("Иркутская область", 38);
        REGION_MAP.put("Калининградская область", 39);
        REGION_MAP.put("Калужская область", 40);
        REGION_MAP.put("Камчатская область", 41);
        REGION_MAP.put("Кемеровская область", 42);
        REGION_MAP.put("Кировская область", 43);
        REGION_MAP.put("Костромская область", 44);
        REGION_MAP.put("Курганская область", 45);
        REGION_MAP.put("Курская область", 46);
        REGION_MAP.put("Ленинградская область", 47);
        REGION_MAP.put("Липецкая область", 48);
        REGION_MAP.put("Магаданская область", 49);
        REGION_MAP.put("Московская область", 50);
        REGION_MAP.put("Мурманская область", 51);
        REGION_MAP.put("Нижегородская область", 52);
        REGION_MAP.put("Новгородская область", 53);
        REGION_MAP.put("Новосибирская область", 54);
        REGION_MAP.put("Омская область", 55);
        REGION_MAP.put("Оренбургская область", 56);
        REGION_MAP.put("Орловская область", 57);
        REGION_MAP.put("Пензенская область", 58);
        REGION_MAP.put("Пермская область", 59);
        REGION_MAP.put("Псковская область", 60);
        REGION_MAP.put("Ростовская область", 61);
        REGION_MAP.put("Рязанская область", 62);
        REGION_MAP.put("Самарская область", 63);
        REGION_MAP.put("Саратовская область", 64);
        REGION_MAP.put("Сахалинская область", 65);
        REGION_MAP.put("Свердловская область", 66);
        REGION_MAP.put("Смоленская область", 67);
        REGION_MAP.put("Тамбовская область", 68);
        REGION_MAP.put("Тверская область", 69);
        REGION_MAP.put("Томская область", 70);
        REGION_MAP.put("Тульская область", 71);
        REGION_MAP.put("Тюменская область", 72);
        REGION_MAP.put("Ульяновская область", 73);
        REGION_MAP.put("Челябинская область", 74);
        REGION_MAP.put("Читинская область", 75);
        REGION_MAP.put("Ярославская область", 76);
        REGION_MAP.put("г. Москва", 77);
        REGION_MAP.put("г. Санкт-Петербург", 78);
        REGION_MAP.put("Еврейская автономная область", 79);
        REGION_MAP.put("Агинский Бурятский автономный округ", 80);
        REGION_MAP.put("Коми-Пермяцкий автономный округ", 81);
        REGION_MAP.put("Корякский автономный округ", 82);
        REGION_MAP.put("Ненецкий автономный округ", 83);
        REGION_MAP.put("Таймырский (Долгано-Ненецкий) автономный округ", 84);
        REGION_MAP.put("Усть-Ордынский Бурятский автономный округ", 85);
        REGION_MAP.put("Ханты-Мансийский автономный округ - Югра", 86);
        REGION_MAP.put("Чукотский автономный округ", 87);
        REGION_MAP.put("Ямало-Ненецкий автономный округ", 89);
        REGION_MAP.put("Республика Крым", 91);
        REGION_MAP.put("г. Севастополь", 92);
        REGION_MAP.put("Иные территории, включая город и космодром Байконур", 99);

        MONTHS_LIST.put("Январь", 1);
        MONTHS_LIST.put("Февраль", 2);
        MONTHS_LIST.put("Март", 3);
        MONTHS_LIST.put("Апрель", 4);
        MONTHS_LIST.put("Май", 5);
        MONTHS_LIST.put("Июнь", 6);
        MONTHS_LIST.put("Июль", 7);
        MONTHS_LIST.put("Август", 8);
        MONTHS_LIST.put("Сентябрь", 9);
        MONTHS_LIST.put("Октябрь", 10);
        MONTHS_LIST.put("Ноябрь", 11);
        MONTHS_LIST.put("Декабрь", 12);

        FIND_PARAMS_LIST.add("Номер билета");
        FIND_PARAMS_LIST.add("Полное название");
        FIND_PARAMS_LIST.add("Сокращенное название");
        FIND_PARAMS_LIST.add("ФИО руководителя");
        FIND_PARAMS_LIST.add("Деятельность/Услуги");

        PAYMENT_LIST.add("Отплачен");
        PAYMENT_LIST.add("Не отплачен");

        RECEIVE_LIST.add("Получен");
        RECEIVE_LIST.add("Не получен");

        PAGE_SIZE.add(10);
        PAGE_SIZE.add(20);
        PAGE_SIZE.add(50);
        PAGE_SIZE.add(100);
    }
}
