package ru.src.logic.implementation;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;

import java.util.HashMap;

public class ListConstants {
    public static final ObservableList<String> MEMBER_STATUS_LIST = FXCollections.observableArrayList();
    public static final ObservableList<String> ORGANIZATION_FORM_LIST = FXCollections.observableArrayList();
    public static final ObservableList<String> ECONOMIC_SECTOR_LIST = FXCollections.observableArrayList();
    public static final ObservableList<String> OWNERSHIP_FORM_LIST= FXCollections.observableArrayList();
    public static final ObservableList<String> ACTIVITY_TYPE_LIST = FXCollections.observableArrayList();
    public static final ObservableList<String> BUSINESS_FORM_LIST = FXCollections.observableArrayList();
    public static final ObservableList<String> INTERESTING_LIST = FXCollections.observableArrayList();
    public static final ObservableList<String> VED_LIST = FXCollections.observableArrayList();
    public static final ObservableList<String> DEDB_STATUS_LIST = FXCollections.observableArrayList();
    public static final ObservableList<String> DISTRICT_LIST = FXCollections.observableArrayList();
    public static final HashMap<Integer, String> REGION_MAP = new HashMap<>();
    public static final HashMap<Integer, String> MONTHS_LIST = new HashMap<>();
    public static final ObservableList<String> FIND_PARAMS_LIST = FXCollections.observableArrayList();

    static {
        MEMBER_STATUS_LIST.add("Актуально стабильно");
        MEMBER_STATUS_LIST.add("Актуально нестабильно");
        MEMBER_STATUS_LIST.add("Актуально долг 1 год");
        MEMBER_STATUS_LIST.add("Актуально долг 2 года");
        MEMBER_STATUS_LIST.add("Актуально долг 3 года");
        MEMBER_STATUS_LIST.add("Заявление на исключение");
        MEMBER_STATUS_LIST.add("Деятельность прекращена");
        MEMBER_STATUS_LIST.add("Потеря связи");
        MEMBER_STATUS_LIST.add("Смена формы собственности");
        MEMBER_STATUS_LIST.add("На исключение");

        ORGANIZATION_FORM_LIST.add("ООО");
        ORGANIZATION_FORM_LIST.add("ПАО");
        ORGANIZATION_FORM_LIST.add("АО");
        ORGANIZATION_FORM_LIST.add("ИАО");
        ORGANIZATION_FORM_LIST.add("ИП");
        ORGANIZATION_FORM_LIST.add("НП");
        ORGANIZATION_FORM_LIST.add("ОАО");
        ORGANIZATION_FORM_LIST.add("ЗАО");
        ORGANIZATION_FORM_LIST.add("СРО");
        ORGANIZATION_FORM_LIST.add("ФОНД");
        ORGANIZATION_FORM_LIST.add("Ассоциация");
        ORGANIZATION_FORM_LIST.add("Союз");
        ORGANIZATION_FORM_LIST.add("Объединение");
        ORGANIZATION_FORM_LIST.add("Самозанятый");
        ORGANIZATION_FORM_LIST.add("ОУ");
        ORGANIZATION_FORM_LIST.add("АНО");
        ORGANIZATION_FORM_LIST.add("Бюджетное учреждение");
        ORGANIZATION_FORM_LIST.add("Госучреждение");

        ECONOMIC_SECTOR_LIST.add("Торговля");
        ECONOMIC_SECTOR_LIST.add("Услуги");
        ECONOMIC_SECTOR_LIST.add("Производство");
        ECONOMIC_SECTOR_LIST.add("Сельскохозяйственная деятельность");
        ECONOMIC_SECTOR_LIST.add("Рыбный промысел");
        ECONOMIC_SECTOR_LIST.add("Лесное хозяйство");
        ECONOMIC_SECTOR_LIST.add("Строительство");
        ECONOMIC_SECTOR_LIST.add("Транспорт");
        ECONOMIC_SECTOR_LIST.add("Связь");
        ECONOMIC_SECTOR_LIST.add("Образование");
        ECONOMIC_SECTOR_LIST.add("Недвижимость");
        ECONOMIC_SECTOR_LIST.add("Бытовое обслуживание");
        ECONOMIC_SECTOR_LIST.add("Полиграфия и издательство");
        ECONOMIC_SECTOR_LIST.add("Туризм");
        ECONOMIC_SECTOR_LIST.add("Компьютерные услуги");
        ECONOMIC_SECTOR_LIST.add("Общественное питание");
        ECONOMIC_SECTOR_LIST.add("Иное");

        OWNERSHIP_FORM_LIST.add("Частная");
        OWNERSHIP_FORM_LIST.add("Государственная");
        OWNERSHIP_FORM_LIST.add("Смешанная");

        ACTIVITY_TYPE_LIST.add("Коммерческая");
        ACTIVITY_TYPE_LIST.add("Не коммерческая");

        BUSINESS_FORM_LIST.add("Микробизнес (<15)");
        BUSINESS_FORM_LIST.add("Малый бизнес (15-100)");
        BUSINESS_FORM_LIST.add("Средний бизнес (101-250)");
        BUSINESS_FORM_LIST.add("Крупный бизнес (>250)");

        INTERESTING_LIST.add("Интересует");
        INTERESTING_LIST.add("Не интересует");

        VED_LIST.add("Да");
        VED_LIST.add("Нет");

        DEDB_STATUS_LIST.add("Имеется");
        DEDB_STATUS_LIST.add("Отсутствует");

        DISTRICT_LIST.add("Аннинский район");
        DISTRICT_LIST.add("Бобровский район");
        DISTRICT_LIST.add("Богучарский район");
        DISTRICT_LIST.add("Борисоглебск Городской округ");
        DISTRICT_LIST.add("Бутурлиновский район");
        DISTRICT_LIST.add("Верхнемамонский район");
        DISTRICT_LIST.add("Верхнехавский район");
        DISTRICT_LIST.add("Воробьевский район");
        DISTRICT_LIST.add("Воронеж Городской округ");
        DISTRICT_LIST.add("Грибановский район");
        DISTRICT_LIST.add("Калачеевский район");
        DISTRICT_LIST.add("Каменский район");
        DISTRICT_LIST.add("Кантемировский район");
        DISTRICT_LIST.add("Каширский район");
        DISTRICT_LIST.add("Лискинский район");
        DISTRICT_LIST.add("Нижнедевицкий район");
        DISTRICT_LIST.add("Нововоронеж Городской округ");
        DISTRICT_LIST.add("Новоусманский район");
        DISTRICT_LIST.add("Новохоперский район");
        DISTRICT_LIST.add("Ольховатский район");
        DISTRICT_LIST.add("Острогожский район");
        DISTRICT_LIST.add("Павловский район");
        DISTRICT_LIST.add("Панинский район");
        DISTRICT_LIST.add("Петропавловский район");
        DISTRICT_LIST.add("Поворинский район");
        DISTRICT_LIST.add("Подгоренский район");
        DISTRICT_LIST.add("Рамонский район");
        DISTRICT_LIST.add("Репьевский район");
        DISTRICT_LIST.add("Россошанский район");
        DISTRICT_LIST.add("Семилукский район");
        DISTRICT_LIST.add("Таловский район");
        DISTRICT_LIST.add("Терновский район");
        DISTRICT_LIST.add("Хохольский район");
        DISTRICT_LIST.add("Эртильский район");

        REGION_MAP.put(1, "Республика Адыгея");
        REGION_MAP.put(2, "Республика Башкортостан");
        REGION_MAP.put(3, "Республика Бурятия");
        REGION_MAP.put(4, "Республика Алтай");
        REGION_MAP.put(5, "Республика Дагестан");
        REGION_MAP.put(6, "Республика Ингушетия");
        REGION_MAP.put(7, "Кабардино-Балкарская Республика");
        REGION_MAP.put(8, "Республика Калмыкия");
        REGION_MAP.put(9, "Карачаево-Черкесская Республика");
        REGION_MAP.put(10, "Республика Карелия");
        REGION_MAP.put(11, "Республика Коми");
        REGION_MAP.put(12, "Республика Марий Эл");
        REGION_MAP.put(13, "Республика Мордовия");
        REGION_MAP.put(14, "Республика Саха (Якутия)");
        REGION_MAP.put(15, "Республика Северная Осетия - Алания");
        REGION_MAP.put(16, "Республика Татарстан (Татарстан)");
        REGION_MAP.put(17, "Республика Тыва");
        REGION_MAP.put(18, "Удмуртская Республика");
        REGION_MAP.put(19, "Республика Хакасия");
        REGION_MAP.put(20, "Чеченская Республика");
        REGION_MAP.put(21, "Чувашская Республика - Чувашия");
        REGION_MAP.put(22, "Алтайский край");
        REGION_MAP.put(23, "Краснодарский край");
        REGION_MAP.put(24, "Красноярский край");
        REGION_MAP.put(25, "Приморский край");
        REGION_MAP.put(26, "Ставропольский край");
        REGION_MAP.put(27, "Хабаровский край");
        REGION_MAP.put(28, "Амурская область");
        REGION_MAP.put(29, "Архангельская область");
        REGION_MAP.put(30, "Астраханская область");
        REGION_MAP.put(31, "Белгородская область");
        REGION_MAP.put(32, "Брянская область");
        REGION_MAP.put(33, "Владимирская область");
        REGION_MAP.put(34, "Волгоградская область");
        REGION_MAP.put(35, "Вологодская область");
        REGION_MAP.put(36, "Воронежская область");
        REGION_MAP.put(37, "Ивановская область");
        REGION_MAP.put(38, "Иркутская область");
        REGION_MAP.put(39, "Калининградская область");
        REGION_MAP.put(40, "Калужская область");
        REGION_MAP.put(41, "Камчатская область");
        REGION_MAP.put(42, "Кемеровская область");
        REGION_MAP.put(43, "Кировская область");
        REGION_MAP.put(44, "Костромская область");
        REGION_MAP.put(45, "Курганская область");
        REGION_MAP.put(46, "Курская область");
        REGION_MAP.put(47, "Ленинградская область");
        REGION_MAP.put(48, "Липецкая область");
        REGION_MAP.put(49, "Магаданская область");
        REGION_MAP.put(50, "Московская область");
        REGION_MAP.put(51, "Мурманская область");
        REGION_MAP.put(52, "Нижегородская область");
        REGION_MAP.put(53, "Новгородская область");
        REGION_MAP.put(54, "Новосибирская область");
        REGION_MAP.put(55, "Омская область");
        REGION_MAP.put(56, "Оренбургская область");
        REGION_MAP.put(57, "Орловская область");
        REGION_MAP.put(58, "Пензенская область");
        REGION_MAP.put(59, "Пермская область");
        REGION_MAP.put(60, "Псковская область");
        REGION_MAP.put(61, "Ростовская область");
        REGION_MAP.put(62, "Рязанская область");
        REGION_MAP.put(63, "Самарская область");
        REGION_MAP.put(64, "Саратовская область");
        REGION_MAP.put(65, "Сахалинская область");
        REGION_MAP.put(66, "Свердловская область");
        REGION_MAP.put(67, "Смоленская область");
        REGION_MAP.put(68, "Тамбовская область");
        REGION_MAP.put(69, "Тверская область");
        REGION_MAP.put(70, "Томская область");
        REGION_MAP.put(71, "Тульская область");
        REGION_MAP.put(72, "Тюменская область");
        REGION_MAP.put(73, "Ульяновская область");
        REGION_MAP.put(74, "Челябинская область");
        REGION_MAP.put(75, "Читинская область");
        REGION_MAP.put(76, "Ярославская область");
        REGION_MAP.put(77, "г. Москва");
        REGION_MAP.put(78, "г. Санкт-Петербург");
        REGION_MAP.put(79, "Еврейская автономная область");
        REGION_MAP.put(80, "Агинский Бурятский автономный округ");
        REGION_MAP.put(81, "Коми-Пермяцкий автономный округ");
        REGION_MAP.put(82, "Корякский автономный округ");
        REGION_MAP.put(83, "Ненецкий автономный округ");
        REGION_MAP.put(84, "Таймырский (Долгано-Ненецкий) автономный округ");
        REGION_MAP.put(85, "Усть-Ордынский Бурятский автономный округ");
        REGION_MAP.put(86, "Ханты-Мансийский автономный округ - Югра");
        REGION_MAP.put(87, "Чукотский автономный округ");
        REGION_MAP.put(89, "Ямало-Ненецкий автономный округ");
        REGION_MAP.put(91, "Республика Крым");
        REGION_MAP.put(92, "г. Севастополь");
        REGION_MAP.put(99, "Иные территории, включая город и космодром Байконур");

        MONTHS_LIST.put(1, "Январь");
        MONTHS_LIST.put(2, "Февраль");
        MONTHS_LIST.put(3, "Март");
        MONTHS_LIST.put(4, "Апрель");
        MONTHS_LIST.put(5, "Май");
        MONTHS_LIST.put(6, "Июнь");
        MONTHS_LIST.put(7, "Июль");
        MONTHS_LIST.put(8, "Август");
        MONTHS_LIST.put(9, "Сентябрь");
        MONTHS_LIST.put(10, "Октябрь");
        MONTHS_LIST.put(11, "Ноябрь");
        MONTHS_LIST.put(12, "Декабрь");

        FIND_PARAMS_LIST.add("Номер билета");
        FIND_PARAMS_LIST.add("Полное название");
        FIND_PARAMS_LIST.add("Сокращенное название");
        FIND_PARAMS_LIST.add("ФИО руководителя");
        FIND_PARAMS_LIST.add("Деятельность/Услуги");
    }
}
